title: Liaqat Ali Shaiz
logo: portfolio/Shaiz1.png
description: >-
  Power BI | Excel | SQL | Python 
theme: jekyll-theme-minimal

# Optional links
github: https://github.com/shaizawan1
email: Liaqat.Ali.Shaiz2@gmail.com
